# Generated by Django 4.2.7 on 2023-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_varified',
            new_name='is_email_verified',
        ),
    ]
