# Generated by Django 4.2.7 on 2023-11-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvarient_sizevarient_product_color_varient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvarient',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizevarient',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
